name: Update git-hooks if changes were made to .git-hooks folder.
on: 
  # Triggers the workflow on push request,
  # but only for the feature branches
  push:
jobs: 
  pagerduty-cli:
    name: Initialize PagerDuty CLI
    runs-on: ubuntu-latest
    container: 
      image: pagerdutycs/pagerduty-cli:latest
      env:
        GITHUB_RUNNER_HOME: /root
      credentials:
        username: ${{ github.actor }}
        password: ${{ secrets.DOCKER_PASSWORD }}
      ports:
        - 80     
  test-job:
    needs: pagerduty-cli
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Checking what version PagerDuty CLI is being used.
        run: |
          pd version
      - name: Running PagerDuty team help command.
        run: |  
          pd team:user:add -h
        shell: bash