name: Publish PagerDuty - CLI Docker image
# Triggers the workflow on manually.
on:
  push:
jobs:
  build-and-push-image-to-repo:
    name: Push Docker image to Github repo.
    runs-on: ubuntu-latest
    permissions:
      packages: write
      contents: read
    steps:
      - name: Checkout
        uses: actions/checkout@v3
      - name: Extract metadata (tags, labels) for Docker
        id: meta
        uses: docker/metadata-action@v4
        with:
          images: fearfactor3/pagerduty-cli
          tags: '0.69'
      - name: Login to GitHub Container Registry
        uses: docker/login-action@v2
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}
      - name: Build and push Docker image
        uses: docker/build-push-action@v3
        with:
          context: .
          push: true
          tags: ghcr.io/${{ steps.meta.outputs.tags }},ghcr.io/${{ steps.meta.outputs.tags }}:latest
          labels: ${{ steps.meta.outputs.labels }}