name: Update git-hooks if changes were made to .git-hooks folder.
on: 
  # Triggers the workflow on push request,
  # but only for the feature branches
  push:
jobs: 
  build:
    runs-on: ubuntu-latest
    container: 
      image: pagerdutycs/pagerduty-cli
      env:
        GITHUB_RUNNER_HOME: /root
      credentials:
        username: ${{ github.actor }}
        password: ${{ secrets.DOCKER_PASSWORD }}
      ports:
        - 80     
    steps:
      - uses: actions/checkout@v2
      - name: Install latest version of pagerduty cli.
        run: |
          pd version
        shell: bash